#!/usr/bin/env perl

use strict;
use warnings;

my %escapecodes = (
  "foreground"             => "10",
  "background"             => "11",
  "border"                 => "708",
  "cursorColor"            => "12",
  "pointerColorBackground" => "13",
  "pointerColorForeground" => "14"
);

for my $i (0..15) { $escapecodes{"color$i"} = "4;$i"; }

my @colors = keys(%escapecodes);

# TODO@cs: get the actual theme colors from Xresources, somehow ...
my %solarizedLight = (
  "foreground"             => "#657b83",
  "background"             => "#fdf6e3",
  "border"                 => "#fdf6e3",
  "cursorColor"            => "#586e75",
  "pointerColorBackground" => "#93a1a1",
  "pointerColorForeground" => "#586e75",
  "color0"                 => "#eee8d5",
  "color1"                 => "#dc322f",
  "color2"                 => "#859900",
  "color3"                 => "#b58900",
  "color4"                 => "#268bd2",
  "color5"                 => "#d33682",
  "color6"                 => "#2aa198",
  "color7"                 => "#073642",
  "color9"                 => "#cb4b16",
  "color8"                 => "#fdf6e3",
  "color10"                => "#93a1a1",
  "color11"                => "#839496",
  "color12"                => "#657b83",
  "color13"                => "#6c71c4",
  "color14"                => "#586e75",
  "color15"                => "#002b36"
);

# TODO@cs: get the actual theme colors from Xresources, somehow ...
my %solarizedDark = (
  "foreground"             => "#839496",
  "background"             => "#002b36",
  "border"                 => "#002b36",
  "cursorColor"            => "#93a1a1",
  "pointerColorBackground" => "#586e75",
  "pointerColorForeground" => "#93a1a1",
  "color0"                 => "#073642",
  "color1"                 => "#dc322f",
  "color2"                 => "#859900",
  "color3"                 => "#b58900",
  "color4"                 => "#268bd2",
  "color5"                 => "#d33682",
  "color6"                 => "#2aa198",
  "color7"                 => "#eee8d5",
  "color9"                 => "#cb4b16",
  "color8"                 => "#002b36",
  "color10"                => "#586e75",
  "color11"                => "#657b83",
  "color12"                => "#839496",
  "color13"                => "#6c71c4",
  "color14"                => "#93a1a1",
  "color15"                => "#fdf6e3"
);

my $currentTheme = "undef";

sub on_start {
  my ($self) = @_;

  if ($currentTheme eq "undef") {
    $currentTheme = "solarizedDark"; # default
  }

  apply_current_theme();
}

sub on_action {
  my ($self, $action) = @_;

  if ($action eq "cycle") {
    if ($currentTheme eq "solarizedDark") { $currentTheme = "solarizedLight"; }
    else { $currentTheme = "solarizedDark"; }
    apply_current_theme();
  } elsif ($action eq "dark") {
    $currentTheme = "solarizedDark";
    apply_current_theme();
  } elsif ($action eq "light") {
    $currentTheme = "solarizedLight";
    apply_current_theme();
  }
}

sub apply_current_theme {
  my $cmd = "";
  my %theme = ();

  if ($currentTheme eq "solarizedDark") { %theme = %solarizedDark; }
  elsif ($currentTheme eq "solarizedLight") { %theme = %solarizedLight; }

  for (@colors) {
    $cmd .= "\033]" . $escapecodes{$_} . ";" . $theme{$_} . "\033\\";
  }

  foreach my $term (urxvt::termlist) { $term->cmd_parse($cmd); }
}
