#!/bin/bash

# Log output:
#
# * 51c333e (12 days) <Gary Bernhardt>  (HEAD -> master) add vim-eunuch
#
# The time massaging regexes start with ^[^<]* because that ensures that they
# only operate before the first "<". That "<" will be the beginning of the
# author name, ensuring that we don't destroy anything in the commit message
# that looks like time.

HASH="%C(yellow)%h%Creset"
TIME="%Cgreen(%ad)%Creset"
AUTHOR="%C(bold blue)<%an>%Creset"
REFS="%C(bold red)%d%Creset"
SUBJECT="%s"

FORMAT="$HASH $TIME $AUTHOR $REFS $SUBJECT"

ANSI_BLACK='\033[30m'
ANSI_BLACK_BOLD='\033[0;30;1m'
ANSI_RED='\033[31m'
ANSI_RED_BOLD='\033[0;31;1m'
ANSI_GREEN='\033[32m'
ANSI_GREEN_BOLD='\033[0;32;1m'
ANSI_YELLOW='\033[33m'
ANSI_YELLOW_BOLD='\033[0;33;1m'
ANSI_BLUE='\033[34m'
ANSI_BLUE_BOLD='\033[0;34;1m'
ANSI_MAGENTA='\033[35m'
ANSI_MAGENTA_BOLD='\033[0;35;1m'
ANSI_CYAN='\033[36m'
ANSI_CYAN_BOLD='\033[0;36;1m'
ANSI_WHITE='\033[37m'
ANSI_WHITE_BOLD='\033[0;37;1m'
ANSI_RESET='\033[0m'

pretty_git_log() {
    local merge_regex='(Merge (branch|remote-tracking branch|pull request) .*$)'
    git log --graph --color --date="format:%Y-%m-%d %H:%M:%S" \
        --pretty="tformat:${FORMAT}" $* |
        # Color merge commits specially
        sed -Ee "s/$merge_regex/$(printf $ANSI_RED)\1$(printf $ANSI_RESET)/" |
        # Page only if needed.
        less --no-init --RAW-CONTROL-CHARS \
          --quit-if-one-screen --chop-long-lines
}
