working_directory = "None"

[general]
ipc_socket = true
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#f6f2ee"
foreground = "#3d2b5a"
dim_foreground = "#302b5d"
bright_foreground = "#643f61"

[colors.cursor]
text = "#3d2b5a"
cursor = "#643f61"

[colors.vi_mode_cursor]
text = "#3d2b5a"
cursor = "#287980"

[colors.search.matches]
foreground = "#3d2b5a"
background = "#a4c1c2"

[colors.search.focused_match]
foreground = "#3d2b5a"
background = "#396847"

[colors.footer_bar]
foreground = "#3d2b5a"
background = "#d3c7bb"

[colors.hints.start]
foreground = "#3d2b5a"
background = "#955f61"

[colors.hints.end]
foreground = "#3d2b5a"
background = "#d3c7bb"

[colors.selection]
text = "#3d2b5a"
background = "#e7d2be"

[colors.normal]
black = "#352c24"
red = "#a5222f"
green = "#396847"
yellow = "#ac5402"
blue = "#2848a9"
magenta = "#6e33ce"
cyan = "#287980"
white = "#f2e9e1"

[colors.bright]
black = "#534c45"
red = "#b3434e"
green = "#577f63"
yellow = "#b86e28"
blue = "#4863b6"
magenta = "#8452d5"
cyan = "#488d93"
white = "#f4ece6"

[colors.dim]
black = "#2d251f"
red = "#8c1d28"
green = "#30583c"
yellow = "#924702"
blue = "#223d90"
magenta = "#5e2baf"
cyan = "#22676d"
white = "#cec6bf"

[[colors.indexed_colors]]
index = 16
color = "#955f61"

[[colors.indexed_colors]]
index = 17
color = "#a440b5"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
builtin_box_drawing = true
size = 12.0

[font.normal]
family = "NotoSansM Nerd Font Mono"
style = "Medium"

[font.bold]
family = "NotoSansM Nerd Font Mono"
style = "Bold"

[font.italic]
family = "NotoSansM Nerd Font Mono"
style = "Medium"

[font.bold_italic]
family = "NotoSansM Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[hints.enabled]]
post_processing = true
regex = "(https:|http:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.command]
args = ["--new-window"]
program = "chromium"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "/home/cs[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
title = "~"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10

