ipc_socket = true
live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#fbf1c7"
index = 229

[[colors.indexed_colors]]
color = "#cc241d"
index = 124

[[colors.indexed_colors]]
color = "#98971a"
index = 106

[[colors.indexed_colors]]
color = "#d79921"
index = 172

[[colors.indexed_colors]]
color = "#458588"
index = 66

[[colors.indexed_colors]]
color = "#b16286"
index = 132

[[colors.indexed_colors]]
color = "#689d6a"
index = 72

[[colors.indexed_colors]]
color = "#7c6f64"
index = 243

[[colors.indexed_colors]]
color = "#928374"
index = 244

[[colors.indexed_colors]]
color = "#9d0006"
index = 88

[[colors.indexed_colors]]
color = "#79740e"
index = 100

[[colors.indexed_colors]]
color = "#b57614"
index = 136

[[colors.indexed_colors]]
color = "#076678"
index = 24

[[colors.indexed_colors]]
color = "#8f3f71"
index = 96

[[colors.indexed_colors]]
color = "#427b58"
index = 66

[[colors.indexed_colors]]
color = "#3c3836"
index = 237

[[colors.indexed_colors]]
color = "#f9f5d7"
index = 230

[[colors.indexed_colors]]
color = "#fbf1c7"
index = 229

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 223

[[colors.indexed_colors]]
color = "#d5c4a1"
index = 250

[[colors.indexed_colors]]
color = "#bdae93"
index = 248

[[colors.indexed_colors]]
color = "#a89984"
index = 246

[[colors.indexed_colors]]
color = "#928374"
index = 244

[[colors.indexed_colors]]
color = "#d65d0e"
index = 166

[[colors.indexed_colors]]
color = "#f2e5bc"
index = 228

[[colors.indexed_colors]]
color = "#7c6f64"
index = 243

[[colors.indexed_colors]]
color = "#665c54"
index = 241

[[colors.indexed_colors]]
color = "#504945"
index = 239

[[colors.indexed_colors]]
color = "#3c3836"
index = 237

[[colors.indexed_colors]]
color = "#282828"
index = 235

[[colors.indexed_colors]]
color = "#af3a03"
index = 130

[colors.bright]
black = "#928374"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#3c3836"
yellow = "#b57614"

[colors.normal]
black = "#f9f5d7"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#7c6f64"
yellow = "#d79921"

[colors.primary]
background = "#f9f5d7"
bright_foreground = "#282828"
foreground = "#3c3836"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
builtin_box_drawing = true
size = 36.0

[font.bold]
family = "Fira Code"
style = "Semibold"

[font.bold_italic]
family = "Fira Code"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Fira Code"
style = "Medium"

[font.normal]
family = "Fira Code"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
post_processing = true
regex = "(https:|http:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.command]
args = ["--new-window"]
program = "chromium"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "/home/cs[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/bash"

[window]
decorations = "none"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
opacity = 1.0
title = "~"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 20
y = 20
