[icons]
icons = "awesome6"

[theme]
theme = "native"

[[block]]
block = "load"
format = "$icon  $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4)"

[[block]]
block = "temperature"
format = "$icon  $average"

[[block]]
block = "temperature"
format = "$icon  $max"
[block.icons_overrides]
thermometer = "\ue040"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"
format = "$icon{  $volume|}"
max_vol = 100

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
format = "$icon{  $volume|}"
max_vol = 100

[[block]]
block = "battery"
driver = "sysfs"
interval = 10
format = "$icon  $percentage{ ~ $time|}"
full_format = "$icon  $percentage{ ~ $time|}"
empty_format = "$icon  $percentage{ ~ $time|}"
not_charging_format = "$icon  $percentage{ ~ $time|}"
missing_format = "$icon"
full_threshold = 95
empty_threshold = 5

[[block]]
block = "time"
interval = 1
format = " $icon  $timestamp.datetime(f:'%Y-%m-%d') "
[block.icons_overrides]
time = "\uf073"

[[block]]
block = "time"
interval = 1
format = " $icon  $timestamp.datetime(f:'%H:%M:%S') "
[block.icons_overrides]
time = "\uf017"
