#!/usr/bin/env ruby

BATTERIES = [0].freeze

charge_full = 0
charge_now = 0

BATTERIES.each do |b|
  charge_full += File.read("/sys/class/power_supply/BAT#{b}/charge_full").to_f
  charge_now += File.read("/sys/class/power_supply/BAT#{b}/charge_now").to_f
end

percentage = charge_now / charge_full * 100.0
puts format("%.2f%", percentage)
