#!/bin/sh

# ------------------------------------------------------------------------------
# Usage
#
# Examples:
#   $ while-success rspec
#   $ while-success make test
#
# Executes the given command (e.g. `rspec`) in a loop as long as it succeeds
# (i.e. exits with status code `== 0`).
# ------------------------------------------------------------------------------

$* # 1st run
while [[ "$?" -eq "0" ]]; do
  $* # Nth run
done
